name: Build Padavan-CAKE MI-R3P

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential gperf bison flex gettext \
          autoconf automake libtool pkg-config git python3 libncurses5-dev \
          libssl-dev zlib1g-dev

    - name: Prepare Toolchain
      run: echo "OK"
